steps:
- name: 'gcr.io/$PROJECT_ID/firebase'
  waitFor: ["-"]
  args: ['/bin/sh', './scripts/slack.sh', 'Starting deployment of $_DOMAIN']
  env:
  - 'SLACK_WEB_HOOK=$_SLACK_WEB_HOOK'
  - 'BUILD=$BUILD_ID'
  - 'PROJECT=$PROJECT_ID'
  - 'REV=$REVISION_ID'
- name: 'gcr.io/$PROJECT_ID/firebase'
  id: yarn
  waitFor: ["-"]
  args: ['/usr/local/bin/yarn']
- name: 'gcr.io/$PROJECT_ID/firebase'
  id: yarn-build
  waitFor:
  - yarn
  args: ['/usr/local/bin/yarn', 'build']
  env:
  - 'REACT_APP_DOMAIN=$_DOMAIN'
  - 'REACT_APP_MEET_DOMAIN=$_MEET_DOMAIN'
  - 'REACT_APP_FIREBASE_API_KEY=$_FIREBASE_API_KEY'
  - 'REACT_APP_FIREBASE_AUTH_DOMAIN=$_FIREBASE_AUTH_DOMAIN'
  - 'REACT_APP_FIREBASE_DATABASE_URL=$_FIREBASE_DATABASE_URL'
  - 'REACT_APP_FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID'
  - 'REACT_APP_FIREBASE_STORAGE_BUCKET=$_FIREBASE_STORAGE_BUCKET'
  - 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$_FIREBASE_MESSAGING_SENDER_ID'
  - 'REACT_APP_FIREBASE_APP_ID=$_FIREBASE_APP_ID'
  - 'REACT_APP_FIREBASE_MEASUREMENT_ID=$_FIREBASE_MEASUREMENT_ID'
  - 'REACT_APP_ALGOLIA_PEOPLE_INDEX=$_ALGOLIA_PEOPLE_INDEX'
  - 'REACT_APP_ALGOLIA_DOCUMENTS_INDEX=$_ALGOLIA_DOCUMENTS_INDEX'
  - 'REACT_APP_ALGOLIA_HIGHLIGHTS_INDEX=$_ALGOLIA_HIGHLIGHTS_INDEX'
  - 'REACT_APP_ALGOLIA_SNAPSHOTS_INDEX=$_ALGOLIA_SNAPSHOTS_INDEX'
  - 'REACT_APP_ERROR_API_KEY=$_ERROR_API_KEY'
  - 'REACT_APP_VERSION=$REVISION_ID'
- name: 'gcr.io/$PROJECT_ID/firebase'
  id: npm-install
  waitFor: ["-"]
  args: ['/usr/local/bin/npm', '--prefix=/workspace/functions', 'install']
- name: 'gcr.io/$PROJECT_ID/firebase'
  id: deploy
  waitFor:
  - yarn-build
  - npm-install
  args: ['/usr/bin/firebase.bash', 'deploy', '--project=$PROJECT_ID', '--force']
  env:
  - 'BUILD=$BUILD_ID'
  - 'PROJECT=$PROJECT_ID'
  - 'REV=$REVISION_ID'
- name: 'gcr.io/$PROJECT_ID/firebase'
  waitFor:
  - deploy
  args: ['/bin/sh', './scripts/slack.sh', 'Finished deployment of $_DOMAIN']
  env:
  - 'SLACK_WEB_HOOK=$_SLACK_WEB_HOOK'
  - 'BUILD=$BUILD_ID'
  - 'PROJECT=$PROJECT_ID'
  - 'REV=$REVISION_ID'
timeout: 30m
